#github actions to echo hello world
name: master
on: [push]
jobs:
  master-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Hello world action step
        run: echo "Hello World"
        shell: bash
